export const anecdote = [
        "C’est le début de l’aventure ! Même si techniquement, la grossesse n’a pas encore commencé, le corps se prépare déjà pour la fécondation.",
        "L'ovulation se prépare. Votre corps se met en condition pour que la fécondation puisse avoir lieu.",
        "Félicitations ! L'ovule fécondé est devenu un embryon. Il commence à voyager vers l'utérus pour s'implanter.",
        "L'embryon mesure environ 0,2 mm. C’est minuscule, mais déjà les premières cellules commencent à se spécialiser !",
        "Le cœur de l’embryon commence à battre, et il mesure maintenant entre 1 et 2 mm !",
        "Les bras et les jambes commencent à se former sous la forme de petits bourgeons.",
        "Les mains et les pieds commencent à se former, et le cerveau se développe rapidement.",
        "Les traits du visage de l’embryon deviennent plus définis, notamment les yeux et le nez.",
        "L’embryon devient un fœtus ! Ses organes internes continuent à se développer.",
        "Le fœtus mesure environ 3 cm et pèse environ 4 grammes. Ses petits doigts et orteils se forment.",
        "Les ongles et les cheveux commencent à pousser. Les organes vitaux sont en place et continuent de se perfectionner.",
        "Votre bébé peut maintenant bouger ses doigts et ses orteils ! Vous ne le sentirez pas encore, mais il s'exerce.",
        "Le fœtus mesure environ 7 à 8 cm. Il peut maintenant sucer son pouce !",
        "Les traits du visage s'affinent, et votre bébé commence à faire des grimaces.",
        "Les os du fœtus deviennent plus solides, et il commence à entendre des sons pour la première fois.",
        "Le fœtus mesure environ 11 cm et peut maintenant ressentir la lumière à travers la paroi de l’utérus.",
        "Le bébé commence à accumuler de la graisse sous sa peau pour se préparer à la vie à l'extérieur.",
        "Il est possible que vous sentiez les premiers mouvements du bébé, un moment inoubliable !",
        "Le système nerveux se développe rapidement. Votre bébé réagit de plus en plus à son environnement.",
        "Votre bébé mesure environ 25 cm de la tête aux pieds, et les battements de son cœur peuvent être entendus avec un stéthoscope.",
        "Les papilles gustatives du bébé sont en place, et il peut goûter le liquide amniotique.",
        "Les yeux du bébé commencent à se développer, mais ils restent fermés pour l’instant.",
        "Le bébé commence à prendre des forces et ses mouvements deviennent plus coordonnés.",
        "Ses poumons se développent rapidement, même s’ils ne sont pas encore tout à fait prêts à fonctionner.",
        "Le bébé est maintenant capable de distinguer les voix et les sons extérieurs.",
        "Les narines du bébé commencent à s'ouvrir, et il s'entraîne à respirer du liquide amniotique.",
        "Le cerveau continue de se développer rapidement et de former des connexions neuronales complexes.",
        "Votre bébé peut maintenant ouvrir et fermer les yeux et réagir à la lumière.",
        "Le bébé commence à rêver ! Les phases de sommeil se régulent peu à peu.",
        "Le cerveau du bébé devient encore plus complexe, et il commence à réguler sa température corporelle.",
        "Le bébé mesure environ 40 cm et prend rapidement du poids pour la dernière ligne droite.",
        "Les ongles de pieds et de mains sont maintenant complètement formés.",
        "Le bébé a de moins en moins d’espace pour bouger, mais ses mouvements restent forts et perceptibles.",
        "Ses poumons continuent de mûrir, et il se prépare à respirer de l’air pour la première fois.",
        "Le bébé adopte souvent la position tête en bas, en préparation de la naissance.",
        "Votre bébé avale encore du liquide amniotique, ce qui aide à développer ses poumons.",
        "Le bébé est considéré comme « à terme » et pourrait naître à tout moment.",
        "Le bébé continue de grossir et ses organes sont prêts à fonctionner de manière autonome.",
        "Le bébé descend dans le bassin, en position pour la naissance. Vous pouvez sentir la pression augmenter.",
        "C’est le grand moment ! Si le bébé n'est pas encore là, il ne devrait plus tarder. Tout est prêt pour la naissance !",  
];